### ISSUE TITLE
Create set of utility modules to be added to any install

### ISSUE THREAD

**Issue by GBirch** [GBirch/massforms8#16] opened 2016-08-23 15:45 UTC
Any MassForms8 project should be easy to administer and support.  We will want standard tools for client staff and the GovNext support team that apply to pretty much every site we build.   

Initial module list at:

https://drive.google.com/open?id=1DJ5A5M81xaQY3Q7mSJkeMINNZgupzzzohdTNYH3MnT8

**Comment by weitzman** [comment] 2016-09-06 15:58
Dupe of #24, #23

**Closed as completed by weitzman** 2016-09-06 15:58 UTC
